---
AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - spec/**/*
    - db/migrate/**/*
    - db/seeds/**/*
    - db/schema.rb
    - config/**/*
    - bin/**/*
  TargetRubyVersion: 3.2
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 10
Style/AsciiComments:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec